import os
from google import genai
from dotenv import load_dotenv

load_dotenv()

def init_gemini():
    """Initializes Gemini with the direct API Key."""
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key or api_key.startswith("your_api"):
         return None
    
    try:
        client = genai.Client(api_key=api_key)
        return client
    except Exception as e:
        print(f"Gemini Init Error: {e}")
        return None

def generate_financial_summary(metrics: dict, execution_time: float) -> str:
    """Uses Gemini 1.5 Flash (Magno's preferred infallible free model) to summarize Infios Revenue."""
    print(f"Generating Infios OS exec summary via Gemini Flash. ROI execution time: {execution_time:.2f}s vs 2h manual.")

    prompt = f"""
    You are a Senior Financial Architect at Google auditing the 'Contas a Receber' closing process at 'Infios'.
    Analyze the following consolidated accounting batch metrics generated by the pipeline in {execution_time:.2f} seconds (previously took 2 hours manually), and output a highly professional, actionable "Executive Summary".

    Data Metrics (All Accounts - Full DRE):
    - Global Revenue Recognition (Credit): R$ {metrics.get('total_revenue', 0):,.2f}
    - Total Reversals (Debit): R$ {metrics.get('total_reversals', 0):,.2f}
    - Total Provisions: R$ {metrics.get('total_provisions', 0):,.2f}
    - Foreign Exchange Variation (Variação Cambial): R$ {metrics.get('variacao_cambial', 0):,.2f}

    Instructions:
    Highlight risks (if any reversals outpace revenue) or simply validate the workflow. Output MUST be in English.
    Keep it strictly under 100 words. Mentality: Google/Amazon Big Tech standard.
    """

    client = init_gemini()
    
    if not client:
         # Graceful degradation mockup for UI validation
         return f"MOCK SUMMARY (GEMINI_API_KEY Not Authenticated in .env): Infios Finance OS pipeline ran in {execution_time:.2f} sec. Global Recognized Revenue: R$ {metrics.get('total_revenue', 0):,.2f}. Matched Reversals: R$ {metrics.get('total_reversals', 0):,.2f}. Added Provisions tracking. All orphan transactions securely dumped to Thiago's review log."

    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
        )
        return response.text
    except Exception as e:
        return f"Vertex/Gemini Execution ERROR: {e}"
